#
# Makefile for the broadcast(TDMB) RF/BB core.
#

obj-$(CONFIG_LGE_BROADCAST)			+= broadcast_tdmb_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_LG2102)		+= lg2102/
obj-$(CONFIG_LGE_BROADCAST_FC8050)		+= fc8050/
#obj-y		+= broadcast_tdmb_drv_if.o
#obj-y		+= lg2102/
#obj-y		+= fc8050/